on:
  push:
    tags:
      - '*'
name: GitHub Packages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      uses: olegtarasov/get-tag@v1
      id: tagName
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Publush
      run: dotnet nuget push "./artifacts/bin/Release/TrashBros.IniUtils.${{ steps.tagName.outputs.tag }}.nupkg" --source "github"
